version: '3.8'

services:
  mysql:
    image: ghcr.io/mysql/mysql-server:8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 5s

  redis:
    image: ghcr.io/docker-library/redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 1s
      retries: 3

  memcached:
    image: ghcr.io/docker-library/memcached:1
    ports:
      - "11211:11211"
    healthcheck:
      test: ["CMD-SHELL", "echo stats | memcached-tool localhost stats > /dev/null 2>&1"]
      interval: 2s
      timeout: 1s
      retries: 3